version: '3.8'

services:
  db:
    env_file:
      - .env-db
    image: bartoszmajkowski/ticket-system-db:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
