version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
  db:
    env_file:
      - .env-db
    image: bartoszmajkowski/ticket-system-db:latest
    pull_policy: always
    ports:
      - "7653:5432"
