version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

  db:
    env_file:
      - .env-db
    image: bartoszmajkowski/ticket-system-db:latest
    pull_policy: always
    ports:
      - "7653:5432"
    networks:
      - ticket-system-network

  backend:
    env_file:
      - .env-backend
    image: bartoszmajkowski/ticket-system-backend:latest
    pull_policy: always
    ports:
      - "5115:5115"
    networks:
      - ticket-system-network

networks:
  ticket-system-network:
    driver: bridge
